import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/common/SideBar";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "IEC",
    template: "%s | IEC",
    default: "IEC",
  },
  description: "Generated by create next app",
  keywords: [""],
  author: "IEC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="scrollbar-none scroll-smooth bg-white">
        <div className="flex h-full">
          <SideBar />
          <div className="w-full bg-gray-300">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
